src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="oc_image")
 * @ORM\Entity(repositoryClass="App\Entity\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255, nullable=true)
     */
    private $alt;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    private $file;
    private $tempfilename;

    public function getFile()
    {
        return $this->file;
    }

    public function setFile(UploadedFile $files = null)
    {
        $this->file = $files;

        // lorsque le formulaire rempli l'objet il se peut que ce soit une modification
        // dans ce cas on regarde si notre objet posssède déjà une image
        if (null !== $this->url) {
            $this->tempfileName = $this->url;

            $this->alt = null;
            $this->url = null;
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        // si on a pas de fichier on annule
        if (null === $this->file)
            return;
        // après le persist ou update on regarde si on a un ancien fichier si oui on le supprime
        if (null !== $this->tempfilename) {
            $oldFile = $this->getUploadRootDir() . '/' . $this->tempfileName;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }
        // on déplace le fichier
        $this->file->move($this->getUploadRootDir(), $this->url);

        unset($this->file);
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function PreUpload()
    {
        // si j'ai pas de fichier alors on annule
        if (null === $this->file)
            return;

        $this->url = $this->getId() . '.' . $this->file->getClientOriginalName();
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempfilename = $this->getUploadRootDir() . '/' . $this->id . "." . $this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempfilename) and !is_dir($this->tempfilename)) {
            // On supprime le fichier
            unlink($this->tempfilename);
        }
    }

    public function getUploadDir()
    {
        return 'uploads/img';
    }

    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    // retourne le chemin du fichier pour l'afficher dans la vue
    public function getPathView()
    {
        return $this->getUploadDir() . '/' . $this->url;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\RefCivilite;
use App\Entity\RefDepartement;
use App\Entity\RefHobbies;
use App\Entity\RefType;
use App\Entity\RefTypeEntity;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;


class UserType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $translator = $options['translator'];

        $builder
            ->add('username', TextType::class, array('required' => true))
            ->add('raisonSocial', TextType::class, array('required' => true))
            ->add('email', EmailType::class, array('required' => true))
            ->add('image', ImageType::class)
            ->add('image', ImageType::class)
            ->add('type', EntityType::class, array(
                    'label' => $translator->trans('lg_civilite'),
                    'class' => RefType::class,
                    'choice_label' => 'type',
                    'empty_data' => 'lg_choisissez',
                    'expanded' => true,
                    'multiple' => false,
                    'required' => true
                )
            )
            ->add('typeEntity', EntityType::class,
                array(
                    'label' => $translator->trans('lg_departement'),
                    'class' => RefTypeEntity::class,
                    'choice_label' => 'typeEntity',
                    'empty_data' => $translator->trans('lg.choisissez'),
                    'expanded' => false,
                    'multiple' => false,
                    'required' => true
                )
            )
        ;

        $builder->addEventListener(
            FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $user = $event->getData();

            // si le user n'a rien envoyé
            if (null == $user) {
                return null;
            }
            // si on n'a pas de password et pas d'id user alors on est en création
            if (!$user->getPassword() || null === $user->getId()) {
                $event->getForm()->add('password', RepeatedType::class, array(
                    'type' => PasswordType::class,
                    'invalid_message' => 'Les mots de passe doivent correspondre',
                    'options' => array('attr' => array('class' => 'password-field')),
                    'required' => true,
//                'first_options'  => array('label' => 'Password'),
//                'second_options' => array('label' => 'Repeat Password'),
                ));
//                    $event->getForm()->add('plainPassword', 'password', array('required' => true));
                $event->getForm()->add('save', SubmitType::class, array('label' => 'Sauvegarder'));
            } else {
                $event->getForm()->add('password', RepeatedType::class, array(
                    'type' => PasswordType::class,
                    'invalid_message' => 'Les mots de passe doivent correspondre',
                    'options' => array('attr' => array('class' => 'password-field')),
                    'required' => false,
//                'first_options'  => array('label' => 'Password'),
//                'second_options' => array('label' => 'Repeat Password'),
                ));
//                    $event->getForm()->add('plainPassword', 'password', array('required' => false));
                $event->getForm()->add('save', SubmitType::class, array('label' => 'Modifier'));
            }

        }
        );
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => User::class,
            'translator' => null
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'imw_form_create_user';
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use Doctrine\ORM\EntityManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Translation\TranslatorInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/user", name="user")
     */
    public function index()
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }

    function logoutAction()
    {
        return $this->redirect($this->generateUrl('fos_user_security_logout'));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     *
     * @Route("person/create", name="imw_create_person")
     */
    function create(Request $request, TranslatorInterface $translator)
    {
        // On crée un objet Advert
        $user = new User();
        $options = array('translator' => $translator);
        // On crée le FormBuilder grâce au service form factory
        $form = $this->createForm(UserType::class, $user, $options);
        // on vérifie que le formulaire est valide
        if ($form->handleRequest($request) && $form->isSubmitted()) {
            if ($form->isValid()) {
                // on enregistre l'image
                // $user->getImage()->upload();
                // on appel notre manager pour enregistrer car new Advert
                $em = $this->getDoctrine()->getManager();
                $password = $form->get('password')->getData();
                $preferences = $form->get('preferences')->getData();

                foreach ($preferences as $preference) {
                    $user->addPreference($preference);
                }
                // on persist l'annonce
                $user->setRoles(array('ROLE_USER'))->setPlainPassword($password)
                    ->setEnabled(true);

                $em->persist($user);
                // on enregistre
                $em->flush();
                // message pour la vue de retour
                $request->getSession()->getFlashBag()->add('notice', 'Création du compte bien enregistré.');
                // redirection vers la vue de l'annonce en récupérant l'id de l'advert Créer
                return $this->redirect($this->generateUrl('oc_platform_editUser', array('id' => $user->getId())));
            }
        }

        // On passe la méthode createView() du formulaire à la vue
        // afin qu'elle puisse afficher le formulaire toute seule
        return $this->render('user/compte.html.twig', array(
            'form' => $form->createView(),
            'user' => $user
        ));
    }

    /**
     * @param $id
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response|\Symfony\Component\Security\Core\Exception\AccessDeniedException
     *
     * @Route("person/edit", name="imw_edit_person")
     */
    function editCompte($id, Request $request, EntityManager $entityManager)
    {
        // On crée un objet User
        $userManager = $entityManager;
        $options = array('translator' => $this->get('translator'));

        if ($this->getUser()->getId() != $id and !$this->isGranted('ROLE_ADMIN')) {
            throw $this->createNotFoundException('fiche non accessible');
        }

        $user = $userManager->getRepository('App:User')->findUserBy(array('id' => $id));

        // On crée le FormBuilder grâce au service form factory
        $form = $this->createForm(UserType::class, $user, $options);
        // on récupère le mot de passe du l'utilisateur
        $password = $user->getPassword();

        // on vérifie que le submit est valide
        $form->handleRequest($request);
        // on vérifie que le formulaire est valide
        if ($form->isValid()) {
            $newPassword = $form->get('password')->getData();
            // on enregistre
            if (!empty($newPassword)) {
                // set plain permet de crypter le nouveau mot de passe
                $user->setPlainPassword($form->get('password')->getData());
            } else {
                // setPassword va concerver le mot de passe crypter déjà existant
                $user->setPassword($password);
            }

//            $userManager->updateUser($user);
            $userManager->flush();
            // message pour la vue de retour
            $request->getSession()->getFlashBag()->add('notice', 'Modification du compte bien enregistré.');
            // redirection vers la vue de l'annonce en récupérant l'id de l'advert Créer
            return $this->redirect($this->generateUrl('imw_edit_person', array('id' => $user->getId())));
        }
        // On passe la méthode createView() du formulaire à la vue
        // afin qu'elle puisse afficher le formulaire toute seule
        return $this->render('user/compte.html.twig', array(
            'form' => $form->createView(),
            'user' => $user
        ));
    }

//    /**
//     * @param $id
//     * @param Request $request
//     * @return \Symfony\Component\HttpFoundation\RedirectResponse
//     * @Route('person/delete", name="imw_person_delete")
//     */
//    function deleteCompte($id, Request $request, EntityManager $entityManager)
//    {
//        // On crée un objet User
//        $userManager = $entityManager;
//        $user = $userManager->findUserBy(array('id' => $id));
//        // on vérifie que le formulaire est valide
//        if ($request->isMethod("GET")) {
//            $userManager->remove($user);
//            $request->getSession()->getFlashBag()->add('notice', 'Suppression du compte bien enregistré.');
//
//            return $this->redirect($this->generateUrl('oc_platform_home'));
//        }
//        // return $this -> redirect($this->generateUrl('oc_platform_editUser',array('id'=>$user -> getId())));
//    }
}

templates/user/compte.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig #}

{% extends "base.html.twig" %}
{% trans_default_domain 'message' %}

{% block title %}
  {{  "lg.entity.creation_compte"|trans }} - {{ parent() }}
{% endblock %}

{% block body %}
	
  {{ include("user/formCompte.html.twig") }}

  <p>
    Vous pouvez créer un compte utilisateur.
  </p>

  <p>
    <a href="{{ path('home') }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à l'accueil
    </a>
  </p>

{% endblock %}

templates/user/formCompte.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/form.html.twig #}
{# Déclaration de variable #}
{% set tailleChamp = 7 %}
{% trans_default_domain 'message' %}

{% if user.id is not null %}
    <h3>{{ "lg.entity.update_compte"|trans }}</h3>
{% else %}
    <h3>{{ "lg.entity.creation_compte"|trans }}</h3>
{% endif %}

<div class="well">
    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}
    <div class="row">
        <div class="col-md-9">
            <div class="form-group">
                {# Génération du label. #}
                {{ form_label(form.raisonSocial, "lg.entity.raison_social"|trans , {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {# Affichage des erreurs pour ce champ précis. #}
                {{ form_errors(form.raisonSocial) }}
                <div class="col-sm-4">
                    {# Génération de l'input. #}
                    {{ form_widget(form.raisonSocial, {'attr': {'class': ''}}) }}
                </div>
            </div>
            <div class="form-group">
                {# Génération du label. #}
                {{ form_label(form.username, "Prénom :", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {# Affichage des erreurs pour ce champ précis. #}
                {{ form_errors(form.username) }}
                <div class="col-sm-4">
                    {# Génération de l'input. #}
                    {{ form_widget(form.username, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group">
                {# Génération du label. #}
                {{ form_label(form.lastname, "Nom :", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {# Affichage des erreurs pour ce champ précis. #}
                {{ form_errors(form.lastname) }}
                <div class="col-sm-4">
                    {# Génération de l'input. #}
                    {{ form_widget(form.lastname, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            {#<div class="form-group">#}
            {# Génération du label. #}
            {#{{ form_label(form.lastname, "Nom :", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}#}
            {# Affichage des erreurs pour ce champ précis. #}
            {#{{ form_errors(form.lastname) }}#}
            {#<div class="col-sm-4">#}
            {# Génération de l'input. #}
            {#{{ form_widget(form.lastname, {'attr': {'class': 'form-control'}}) }}#}
            {#</div>#}
            {#</div>#}
            <div class="form-group">
                {{ form_label(form.departement, 'lg.departement'|trans, {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {{ form_errors(form.departement) }}
                <div class="col-sm-4">
                    {{ form_widget(form.departement, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group">
                {# Génération du label. #}
                {{ form_label(form.dateNaissance, "lg.date_naissance"|trans , {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {# Affichage des erreurs pour ce champ précis. #}
                {{ form_errors(form.dateNaissance) }}
                <div class="col-sm-4">
                    {# Génération de l'input. #}
                    {{ form_widget(form.dateNaissance, {'attr': {'class': 'form-control datepicker'}}) }}
                </div>
            </div>
            {# Idem pour un autre champ. #}
            <div class="form-group">
                {{ form_label(form.email, "E-mail :", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {{ form_errors(form.email) }}
                <div class="col-sm-4">
                    {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            {#<div class="form-group">#}
            {#{{ form_label(form.email.second, "Confirmez votre e-mail :", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}#}
            {#{{ form_errors(form.email.second) }}#}
            {#<div class="col-sm-4">#}
            {#{{ form_widget(form.email.second, {'attr': {'class': 'form-control'}}) }}#}
            {#</div>#}
            {#</div>#}
            <div class="form-group">
                {{ form_label(form.password.first, "Mot de passe :", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {{ form_errors(form.password.first) }}
                <div class="col-sm-4">
                    {{ form_widget(form.password.first, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group">
                {{ form_label(form.password.second, "Confirmez le mot de passe :", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {{ form_errors(form.password.second) }}
                <div class="col-sm-4">
                    {{ form_widget(form.password.second, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            {#<div class="form-group">#}
            {#{{ form_label(form.roles, "Droit utilisateur :", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}#}
            {#{{ form_errors(form.roles) }}#}
            {#<div class="col-sm-7">#}
            {#{{ form_widget(form.roles, {'attr': {'class': 'form-control'}}) }}#}
            {#</div>#}
            {#</div>#}
            <div class="form-group">
                {{ form_label(form.image.file, "Photo profile :", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                {{ form_errors(form.image.file) }}
                <div class="col-sm-4">
                    {{ form_widget(form.image.file, {'attr': {'class': ''}}) }}
                </div>
            </div>
            <fieldset>
                <legend>{{ 'lg.preferences'|trans }}</legend>
                <div class="form-group">
                    {{ form_label(form.preferences, 'lg.passe_temps'|trans, {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                    {{ form_errors(form.preferences) }}
                    <div class="col-sm-4">
                        {{ form_widget(form.preferences, {'attr': {'class': ''}}) }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form_label(form.preferenceDepartements, 'lg.preferences_departements'|trans, {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                    {{ form_errors(form.preferenceDepartements) }}
                    <div class="col-sm-4">
                        {{ form_widget(form.preferenceDepartements, {'attr': {'class': ''}}) }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form_label(form.preferenceSexes, 'lg.preferences_civilite'|trans, {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
                    {{ form_errors(form.preferenceSexes) }}
                    <div class="col-sm-4">
                        {{ form_widget(form.preferenceSexes, {'attr': {'class': ''}}) }}
                    </div>
                </div>
            </fieldset>
            {#<div class="form-group">#}
            {#{{ form_label(form.enabled, "Actif / Inactif :", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}#}
            {#{{ form_errors(form.enabled) }}#}
            {#<div class="col-sm-4">#}
            {#{{ form_widget(form.enabled, {'attr': {'class': 'form-control'}}) }}#}
            {#</div>#}
            {#</div>#}
            {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
            {% if user.id is not null and is_granted('ROLE_ADMIN') %}
                <a class="btn btn-danger btn-mini pull-right col-sm-2 "
                   href="{{ path('oc_platform_deleteUser', {'id': user.id}) }}">Supprimer</a>
            {% endif %}
            {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary pull-right col-sm-2','style':'margin-right:5px;'}}) }}
        </div>
        <div class="col-md-3">
            {% if user.id is not null %}
                {% if user.image.url is defined  %}
                    <div class="col-sm-5 pull-right">
                        <a class="" href="{{ asset(user.image.pathView) }}" title="{{ user.image.alt }}">
                            <img src="{{ asset(user.image.PathView) }}" alt="{{ user.image.alt }}" style="width:100px">
                        </a>
                    </div>
                {% else %}
                    {% set fileSexe = '' %}
                    {% if user.civilite %}
                        {% if user.civilite.civilite == 'Monsieur' %}
                            {% set fileSexe = 'homme' %}
                        {% elseif user.civilite.civilite == 'Madame' or user.civilite == 'Mademoiselle' %}
                            {% set fileSexe = 'femme' %}
                        {% else %}
                            {% set fileSexe = 'deux' %}
                        {% endif %}
                    {% endif %}

                    {% set pathToBundle = 'bundles/ocplatform/img/avatar-' ~ fileSexe ~ '.jpg' %}
                    <div class="col-sm-5 pull-right">
                        <a class="" href="{{ asset(pathToBundle) }}" title="avatar-{{ fileSexe }}">
                            <img src="{{ asset(pathToBundle) }}" alt="avatar-{{ fileSexe }}" style="width:100px">
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>


    {# Génération automatique des champs pas encore écrits.
       Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
       et tous les champs cachés (type « hidden »). #}
    {{ form_rest(form) }}

    {# Fermeture de la balise <form> du formulaire HTML #}
    {{ form_end(form) }}
</div>

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'src/Controller/UserController.php'|file_link(0) }}">src/Controller/UserController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'templates/user/index.html.twig'|file_link(0) }}">templates/user/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}